version: '3.9'

services:
  db:
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  farm_calendar:
    build: .
    image: ghcr.io/openagri-eu/farmcalendar:latest
    command: /var/www/entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      LOGGING_LEVEL: ${LOGGING_LEVEL}
      GATEKEEPER_LOGIN_URL: ${GATEKEEPER_LOGIN_URL}
      JWT_SIGNING_KEY: ${JWT_SIGNING_KEY}
      JWT_COOKIE_NAME: ${JWT_COOKIE_NAME}
    # volumes:
    #   - ./:/var/www
